# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20170701_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='iduser',
            name='pictureURL',
            field=models.CharField(default=datetime.datetime(2017, 7, 1, 15, 9, 33, 803387, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
