# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_iduser_pictureurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iduser',
            name='pictureURL',
            field=models.CharField(max_length=400),
        ),
    ]
