# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_iduser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iduser',
            name='id',
        ),
        migrations.AlterField(
            model_name='iduser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
