# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20170701_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iduser',
            name='id',
        ),
        migrations.AddField(
            model_name='iduser',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
