# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_auto_20170701_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewIDUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('pictureURL', models.CharField(max_length=400)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
